runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mywebsite.wsgi

runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

manual_scaling:
  instances: 1

beta_settings:
    cloud_sql_instances: '<Cloud SQL Instance connection name>' # in format '<PROJECT_ID>:<ZONE>:<INSTANCE_NAME>' (and inside strings)

